### PR TITLE
NSFW button

### PR DESCRIPTION
**Pull request by erinclemmer**
I added a nsfw button that turns grey when clicked. This disallows the user to see nsfw posts. This works with the cookies.js that was already wrote and will remember the decision for two days.  
I have not used handlebars before so the icon may not be inserted the best way

### CODE REVIEW

**Comment by gabranches** [comment]
Thanks! Will check this out tonight when I get home.

**Comment by gabranches** [comment]
This should be going live in a few minutes - Just one change that I made: I want to keep the top bar as less cluttered as possible, so I took out the NSFW image; however, the rest is untouched, so you should be able to hide the NSFW threads by going to the options page. Thank you for the great work!

**Comment by erinclemmer** [comment]
Alright, I didn't think about having it in the options menu until after I put the image on there.

**Comment by erinclemmer** [comment]
And no problem, I'm just happy to be working on something I'll actually use :)

**Pull request closed without merging**
